services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    command: serve
    networks:
      - ollama-network
      - ecommerce_scraper_default
    mem_limit: 6g  # Set a memory limit for the Ollama container

  ollamadb:
    image: postgres:14
    container_name: ollama-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ollama_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ollama-network

  django:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_DB_URL=postgresql://username:password@ollama-db/ollama_data
      - ECOMMERCE_DB_URL=postgresql://username:password@ecommerce_scraper-db-1/ecommerce_data
    depends_on:
      - ollama
      - ollamadb
    networks:
      - ollama-network
      - ecommerce_scraper_default

networks:
  ollama-network:
    driver: bridge
  ecommerce_scraper_default:
    external: true

volumes:
  postgres_data:
