services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    command: serve

  ollamadb:
    image: postgres:14
    container_name: ollama-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ollama_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
  shared-network:
    external: true  # Use the shared network

volumes:
  postgres_data:
